name: Build Kivy APK

on:
  workflow_dispatch:   # запуск вручную
  push:
    branches: [ main ] # можно запускать при пуше в main

jobs:
  build:
    runs-on: ubuntu-20.04   # важна версия Ubuntu
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git zip unzip openjdk-17-jdk
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-kivy-apk
          path: bin/*.apk
