name: Build Kivy APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build with Docker (kivy/buildozer)
        run: |
          docker run --rm -v ${{ github.workspace }}:/home/user/app \
            kivy/buildozer buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-kivy-apk
          path: bin/*.apk
